# Generated by Django 4.2.3 on 2023-07-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jea', 'jeans'), ('chau', 'chaussures'), ('jup', 'jupes'), ('pul', 'pulls'), ('top', 'T-shirts'), ('vest', 'vestes'), ('rob', 'robes'), ('combi', 'combinaisons'), ('blaz', 'blazers'), ('mail', 'maillot de bain'), ('acc', 'accessoires'), ('bc', 'Beauté & Cosmétique')], max_length=10),
        ),
    ]
