# Generated by Django 4.2.3 on 2023-07-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jea', 'jeans'), ('chau', 'chaussures'), ('jup', 'jupes'), ('pul', 'pulls'), ('top', 'T-shirts'), ('vest', 'vestes'), ('rob', 'robes'), ('combi', 'combinaisons'), ('blaz', 'blazers'), ('mail', 'maillot de bain'), ('lun', 'lunettes'), ('bag', 'sacs'), ('hat', 'chapeaux'), ('ceint', 'ceintures'), ('mech', 'meches'), ('bc', 'Beauté & Cosmétique')], max_length=16),
        ),
    ]
