# Generated by Django 4.2.3 on 2023-08-01 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Paris & Paris', 'Paris & Paris'), ('Melun & Melun', 'Melun & Melun'), ('Versailles & Versailles', 'Versailles & Versailles'), ('Evry & Evry', 'Evry & Evry'), ('Nanterre & Nanterre', 'Nanterre & Nanterre'), ('Bobigny & Bobigny', 'Bobigny & Bobigny'), ('Créteil & Créteil', 'Créteil & Créteil'), ('Pontoise & Pontoise', 'Pontoise & Pontoise'), ('Seine-et-Marne & Seine-et-Marne', 'Seine-et-Marne & Seine-et-Marne'), ('Essone & Essone', 'Essone & Essone'), ('Yvelines & Yvelines', 'Yvelines & Yvelines'), ('Hauts-de-seine & Hauts-de-seine', 'Hauts-de-seine & Hauts-de-seine'), ('Seine-Saint-Denis & Seine-Saint-Denis', 'Seine-Saint-Denis & Seine-Saint-Denis'), ('Val-de-Marne & Val-de-Marne', 'Val-de-Marne & Val-de-Marne'), ('Boulogne-Billancourt & Boulogne-Billancourt', 'Boulogne-Billancourt & Boulogne-Billancourt'), ('Montreuil & Montreuil', 'Montreuil & Montreuil'), ('Courbevoie & Courbevoie', 'Courbevoie & Courbevoie'), ('Colombes & Colombes', 'Colombes & Colombes'), ('Vitry-sur-Seine & Vitry-sur-Seine', 'Vitry-sur-Seine & Vitry-sur-Seine'), ('Argenteuil & Argenteuil', 'Argenteuil & Argenteuil'), ('15e Arrondissement de Paris & 15e Arrondissement de Paris', '15e Arrondissement de Paris & 15e Arrondissement de Paris'), ('14e Arrondissement de Paris & 14e Arrondissement de Paris', '14e Arrondissement de Paris & 14e Arrondissement de Paris'), ('13e Arrondissement de Paris & 13e Arrondissement de Paris', '13e Arrondissement de Paris & 13e Arrondissement de Paris'), ('12e Arrondissement de Paris & 12e Arrondissement de Paris', '12e Arrondissement de Paris & 12e Arrondissement de Paris'), ('11e Arrondissement de Paris & 11e Arrondissement de Paris', '11e Arrondissement de Paris & 11e Arrondissement de Paris'), ('10e Arrondissement de Paris & 10e Arrondissement de Paris', '10e Arrondissement de Paris & 10e Arrondissement de Paris'), ('9e Arrondissement de Paris & 9e Arrondissement de Paris', '9e Arrondissement de Paris & 9e Arrondissement de Paris'), ('8e Arrondissement de Paris & 8e Arrondissement de Paris', '8e Arrondissement de Paris & 8e Arrondissement de Paris'), ('7e Arrondissement de Paris & 7e Arrondissement de Paris', '7e Arrondissement de Paris & 7e Arrondissement de Paris'), ('6e Arrondissement de Paris & 6e Arrondissement de Paris', '6e Arrondissement de Paris & 6e Arrondissement de Paris'), ('11e Arrondissement de Paris & 11e Arrondissement de Paris', '11e Arrondissement de Paris & 11e Arrondissement de Paris'), ('5e Arrondissement de Paris & 5e Arrondissement de Paris', '5e Arrondissement de Paris & 5e Arrondissement de Paris'), ('4e Arrondissement de Paris & 4e Arrondissement de Paris', '4e Arrondissement de Paris & 4e Arrondissement de Paris'), ('3e Arrondissement de Paris & 3e Arrondissement de Paris', '3e Arrondissement de Paris & 3e Arrondissement de Paris'), ('2e Arrondissement de Paris & 2e Arrondissement de Paris', '2e Arrondissement de Paris & 2e Arrondissement de Paris'), ('1e Arrondissement de Paris & 1e Arrondissement de Paris', '1e Arrondissement de Paris & 1e Arrondissement de Paris')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
