# Generated by Django 4.2.3 on 2023-08-18 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('stripe_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Paris & Paris', 'Paris & Paris'), ('Melun & Melun', 'Melun & Melun'), ('Versailles & Versailles', 'Versailles & Versailles'), ('Evry & Evry', 'Evry & Evry'), ('Nanterre & Nanterre', 'Nanterre & Nanterre'), ('Bobigny & Bobigny', 'Bobigny & Bobigny'), ('Créteil & Créteil', 'Créteil & Créteil'), ('Pontoise & Pontoise', 'Pontoise & Pontoise'), ('Seine-et-Marne & Seine-et-Marne', 'Seine-et-Marne & Seine-et-Marne'), ('Essone & Essone', 'Essone & Essone'), ('Yvelines & Yvelines', 'Yvelines & Yvelines'), ('Hauts-de-seine & Hauts-de-seine', 'Hauts-de-seine & Hauts-de-seine'), ('Seine-Saint-Denis & Seine-Saint-Denis', 'Seine-Saint-Denis & Seine-Saint-Denis'), ('Val-de-Marne & Val-de-Marne', 'Val-de-Marne & Val-de-Marne'), ('Boulogne-Billancourt & Boulogne-Billancourt', 'Boulogne-Billancourt & Boulogne-Billancourt'), ('Montreuil & Montreuil', 'Montreuil & Montreuil'), ('Courbevoie & Courbevoie', 'Courbevoie & Courbevoie'), ('Colombes & Colombes', 'Colombes & Colombes'), ('Vitry-sur-Seine & Vitry-sur-Seine', 'Vitry-sur-Seine & Vitry-sur-Seine'), ('Argenteuil & Argenteuil', 'Argenteuil & Argenteuil'), ('15e Arrondissement de Paris & 15e Arrondissement de Paris', '15e Arrondissement de Paris & 15e Arrondissement de Paris'), ('14e Arrondissement de Paris & 14e Arrondissement de Paris', '14e Arrondissement de Paris & 14e Arrondissement de Paris'), ('13e Arrondissement de Paris & 13e Arrondissement de Paris', '13e Arrondissement de Paris & 13e Arrondissement de Paris'), ('12e Arrondissement de Paris & 12e Arrondissement de Paris', '12e Arrondissement de Paris & 12e Arrondissement de Paris'), ('11e Arrondissement de Paris & 11e Arrondissement de Paris', '11e Arrondissement de Paris & 11e Arrondissement de Paris'), ('10e Arrondissement de Paris & 10e Arrondissement de Paris', '10e Arrondissement de Paris & 10e Arrondissement de Paris'), ('9e Arrondissement de Paris & 9e Arrondissement de Paris', '9e Arrondissement de Paris & 9e Arrondissement de Paris'), ('8e Arrondissement de Paris & 8e Arrondissement de Paris', '8e Arrondissement de Paris & 8e Arrondissement de Paris'), ('7e Arrondissement de Paris & 7e Arrondissement de Paris', '7e Arrondissement de Paris & 7e Arrondissement de Paris'), ('6e Arrondissement de Paris & 6e Arrondissement de Paris', '6e Arrondissement de Paris & 6e Arrondissement de Paris'), ('11e Arrondissement de Paris & 11e Arrondissement de Paris', '11e Arrondissement de Paris & 11e Arrondissement de Paris'), ('5e Arrondissement de Paris & 5e Arrondissement de Paris', '5e Arrondissement de Paris & 5e Arrondissement de Paris'), ('4e Arrondissement de Paris & 4e Arrondissement de Paris', '4e Arrondissement de Paris & 4e Arrondissement de Paris'), ('3e Arrondissement de Paris & 3e Arrondissement de Paris', '3e Arrondissement de Paris & 3e Arrondissement de Paris'), ('2e Arrondissement de Paris & 2e Arrondissement de Paris', '2e Arrondissement de Paris & 2e Arrondissement de Paris'), ('1e Arrondissement de Paris & 1e Arrondissement de Paris', '1e Arrondissement de Paris & 1e Arrondissement de Paris')], default='En attente', max_length=57)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
